version: 2.1
jobs:
  build:
    working_directory: ~/FrontEnd
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout:
          path: ~/Frontend
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test