version: 2.1
jobs:
  frontend-test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - run:
          name: Install Dependencies
          command: cd Frontend && npm install
      - run:
          name: Run tests
          command: cd Frontend && npm run test
workflows:
  version: 2
  SEPT-ci:
    jobs: 
      - frontend-test