version: 2.1

workflows:
  SEPT-ci:
    jobs: 
      - frontend-test:
          context:
            - dockerdetails

jobs:
  frontend-test:
    docker:
      - image: circleci/node:10.16.3
      - image: septmovinghouses/sept:latest
        auth: 
          username: septmovinghouses
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/FrontEnd
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - run:
          name: Install Dependencies
          command: cd FrontEnd && npm install
      - run:
          name: Run tests
          command: cd FrontEnd && npm run test

